# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &defaults
  secret_key_base: 86e56206aedef14834136f474ff9ef01d8b657fcca25f0b82dc649172ea7419f7616e25864a16473e8116d274683a24c2e0822d3e7e33e0d99439568290c6469
  twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %> 
  twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %> 
  twitter_access_token: <%= ENV['TWITTER_ACCESS_TOKEN'] %> 
  twitter_access_secret: <%= ENV['TWITTER_ACCESS_SECRET'] %> 

secured: &secured
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  <<: *secured

production:
  <<: *defaults
  <<: *secured